---
# Playbook: Provision and configure Nginx for Blitz Tactics
# Usage:
#   ansible-playbook -i <inventory> ansible/nginx.yml \
#     -e server_name_main=blitztactics.com \
#     -e server_name_www=www.blitztactics.com \
#     -e app_root=/home/rails/blitz-tactics/public \
#     -e upstream_port=3000

- hosts: all
  become: true
  vars:
    # Override via -e if needed
    server_name_main: blitztactics.com
    server_name_www: www.blitztactics.com
    app_root: /home/rails/blitz-tactics/public
    upstream_port: 3000
    nginx_site_filename: "blitztactics.conf"
    ssl_cert_path: "/etc/letsencrypt/live/{{ server_name_main }}/fullchain.pem"
    ssl_key_path: "/etc/letsencrypt/live/{{ server_name_main }}/privkey.pem"

  handlers:
    - name: reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded

  tasks:
    - name: Ensure APT cache is up to date
      ansible.builtin.apt:
        update_cache: true

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Ensure Nginx is enabled and started
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Ensure sites-available directory exists
      ansible.builtin.file:
        path: /etc/nginx/sites-available
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Ensure sites-enabled directory exists
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Deploy Blitz Tactics Nginx site config
      ansible.builtin.template:
        src: templates/nginx_site.conf.j2
        dest: "/etc/nginx/sites-available/{{ nginx_site_filename }}"
        owner: root
        group: root
        mode: '0644'
      notify: reload nginx

    - name: Enable Blitz Tactics site
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/{{ nginx_site_filename }}"
        dest: "/etc/nginx/sites-enabled/{{ nginx_site_filename }}"
        state: link
        force: true
      notify: reload nginx

    - name: Test Nginx configuration
      ansible.builtin.command: nginx -t
      register: nginx_test
      changed_when: false
      failed_when: nginx_test.rc != 0

    - name: Reload Nginx to apply changes
      ansible.builtin.service:
        name: nginx
        state: reloaded
